# Generated by Django 4.1a1 on 2022-07-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[("usd", "USD"), ("krw", "KRW")],
                default="krw",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("kr", "Korean")],
                default="kr",
                max_length=2,
            ),
        ),
    ]
