# Generated by Django 4.1b1 on 2022-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_secret",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
