# Generated by Django 4.1b1 on 2022-07-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_email_confirmed_user_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_method",
            field=models.CharField(
                choices=[("email", "Email"), ("github", "Github"), ("kakao", "Kakao")],
                default="email",
                max_length=6,
            ),
        ),
    ]
