# Generated by Django 4.1a1 on 2022-06-19 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversations", "0002_alter_message_conversation_alter_message_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="conversations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
