# Generated by Django 4.1a1 on 2022-06-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="message",
            new_name="review",
        ),
    ]
